services:
  web:
    build: .
    command: bash -lc "bundle exec rails db:prepare && bundle exec rails server -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: lab
      LAB_MODE: "1"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    tty: true
    stdin_open: true

volumes:
  bundle_cache:
